project:
  type: website
  output-dir: docs
website:
  title: "Rebecca Martinez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: field_photos
        text: Field Photos
      - href: resume.qmd
        text: Resume
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/RebeccaLMartinez
        aria-label: GitHub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

