project:
  type: website
  output-dir: docs

website:
  title: "Rebecca Martinez"
  page-footer:
    left: "© 2025 Rebecca Martinez"
    right:
      - icon: github
        href: https://github.com/RebeccaLMartinez
      - icon: envelope
        href: mailto:rebecca_martinez@ucsb.edu
      
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    include-after-body: _footer.html
    